require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "Greetings"
task :hello_world do
  puts "Hello World, Prince"
end
